### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/udemy#1]
gerekli düzeltmeyi yaparak:

1. favicon.ico dosyasını kendi kodunun dizini içine koy
2. aşağıdaki satırdaki referansı düzelt

https://github.com/kcagdass/udemy/blob/dfe841a53a7b3b9e0901de1b1aca08354fa0debf/index.html#L9

![image](https://user-images.githubusercontent.com/1656836/46574820-39730100-c9b2-11e8-9c36-fb6c0f874589.png)

#6 ile ilintili

**Comment by kburakozdemir** [comment]
bu da aynen duruyor. ama işi kapatmışsın?!?

**Comment by kcagdass** [comment]
#12 ile kapatıldı

**Comment by kcagdass** [comment]
#12 ile kapatıldı
