### ISSUE TITLE
inline style

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/udemy#2]
bu satırda 2 tane hata var:

https://github.com/kcagdass/udemy/blob/29202ceefae8b9e4eed7605254124919fc753a48/index.html#L117

1. inline css kullanmışsın? bunu custom.css için al
2. `property` ve `value` kısımlarını yanlış yazmışsın.

**Comment by kburakozdemir** [comment]
1. ancak yazdığın şekilde çalışmaz. 
2. çok zorda kalmadıkça `inline styling` iyi birşey değildir.

**Comment by kcagdass** [comment]
tamam düzeltiyorum onu

**Comment by kburakozdemir** [comment]
> tamam düzeltiyorum onu

'düzeltiyorum demene' gerek yok. zaten buraya düzeltmen üzere bir çeşit  `code review` olarak Issue açıyorum. 
1. yapmaya başlayacağın zaman kendine `assign` et issue'yu. bu senin yapmakta olduğun anlamına gelir.
2. bitirince de 
```bash 
git add .
git commit -m "anlamlı bir commit mesajı yazmak gerekir"
git push
```
ile yaptığın işi gönder.

**Comment by kcagdass** [comment]
tamamdır

Burak Özdemir <notifications@github.com>, 6 Eki 2018 Cmt, 22:43 tarihinde
şunu yazdı:

**Comment by kcagdass** [comment]
css içine alındı
