### ISSUE TITLE
README.md dosyasına eklenecek link

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/udemy#3]
Bahsedilen eğitimde kullanılacak site linki bu... Bu linki de README.md dosyasına ekle.

http://www.makerbased.com/oml/

**Comment by kcagdass** [comment]
ekledim

**Comment by kburakozdemir** [comment]
'ekledim' demene gerek yok. issue'yu kapat. hala açık duruyor. issue'yu düzeltince, close et yani kapat.

**Comment by kcagdass** [comment]
link eklendi

**Comment by kcagdass** [comment]
link eklendi
