### ISSUE TITLE
2 adet title tag

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/udemy#5]
2 adet title tag var.
https://github.com/kcagdass/udemy/blob/68796d3e2b871fe68c0471b45e70a40f9bcf9536/index.html#L11
https://github.com/kcagdass/udemy/blob/68796d3e2b871fe68c0471b45e70a40f9bcf9536/index.html#L32

1. bir sayfada iki adet `title` tag olmaz.
2. `title` tag `head` tag'inin içinde olmalı.

**Comment by kburakozdemir** [comment]
ben yanlış mı görüyorum? bu işi yapmamışsın ama kapatmışsın?

![image](https://user-images.githubusercontent.com/1656836/46847681-464a8700-cdee-11e8-8b65-35c1134ca8e8.png)

**Comment by kcagdass** [comment]
title lar düzeltildi
