### ISSUE TITLE
Fazla satır

### ISSUE THREAD

**Issue by kburakozdemir** [kcagdass/udemy#6]
bu satır
1. fazla
2. `head` tag'inin dışında.
https://github.com/kcagdass/udemy/blob/68796d3e2b871fe68c0471b45e70a40f9bcf9536/index.html#L33
3. zaten 9. satırda bu var. 33. satırı sil.
https://github.com/kcagdass/udemy/blob/9e1da52e7b92cf1367aea66968132ad3cd3782d9/index.html#L9
4. #1 nolu issue'da bunun düzeltilmesi gerektiğinden bahsetmiştim.

**Comment by kburakozdemir** [comment]
bu da aynen duruyor. ama işi kapatmışsın?!?

**Comment by kcagdass** [comment]
işletim sistemim değişince, burdan zip dosyası indirdim oda açılmadı bende kopyalayıp düzeltmeleri yaptım. git ile yaptığım işin kopyasını attım. başka nasıl olabilir bilmiyorum

**Comment by kburakozdemir** [comment]
> işletim sistemim değişince, burdan zip dosyası indirdim oda açılmadı bende kopyalayıp düzeltmeleri yaptım. git ile yaptığım işin kopyasını attım. başka nasıl olabilir bilmiyorum

git tam da böyle olmasın diye var. git eğitimine baktın mı? https://docs.binbiriz.com/training/#3-versiyon-kontrolu

biraz git konusunda da çalışır mısın?
